apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-router
  namespace: kube-system
  labels:
    k8s-app: kube-router
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-router
    spec:
      hostNetwork: true
      containers:
      - name: kube-router
        image: cloudnativelabs/kube-router
        args: ["--run-router=false", "--run-firewall=false", "--run-service-proxy=true"]
        securityContext:
          privileged: true
        imagePullPolicy: Always
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - mountPath: /lib/modules
            name: lib-modules
            readOnly: true
          - mountPath: /etc/cni/net.d/10-kuberouter.conf
            name: cni-conf-dir
          - mountPath: /var/lib/kube-router/kubeconfig
            name: kubeconfig
      volumes:
        - name: lib-modules
          hostPath:
              path: /lib/modules
        - name: cni-conf-dir
          hostPath:
              path: /etc/cni/net.d/10-kuberouter.conf
        - name: kubeconfig
          hostPath:
              path: /var/lib/kube-router/kubeconfig
